// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv03-pK7ys-w783t7iV2_eBJqeKpIM0DU',
    appId: '1:911473772488:android:bc5a42cee75c49fd7da2fd',
    messagingSenderId: '911473772488',
    projectId: 'fourinarow-950d4',
    databaseURL: 'https://fourinarow-950d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fourinarow-950d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtvuL7VN6F52VsGIQGDz1gkn5BPl296II',
    appId: '1:911473772488:ios:9620661ccb4efce67da2fd',
    messagingSenderId: '911473772488',
    projectId: 'fourinarow-950d4',
    databaseURL: 'https://fourinarow-950d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fourinarow-950d4.appspot.com',
    iosClientId: '911473772488-dmpcmpf7clvtof969cu4auc0lvufkvns.apps.googleusercontent.com',
    iosBundleId: 'com.fourinarowmusab.fourInARow',
  );
}
